[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "djangobible"
author = "Nathan Patton"
author-email = "npatton@gmail.com"
home-page = "https://github.com/avendesora/django-bible"
classifiers = ["License :: OSI Approved :: MIT License"]
description-file = "README.md"
requires-python = ">=3.6"
requires = [
    "Django >=3.0.0",
    "pythonbible >=0.1.3",
]

[tool.flit.metadata.requires-extra]
test = [
    "pytest-django >=3.10.0",
]
doc = [
]
dev = [
    "bandit >=1.6.2",
    "black >=20.8b1",
    "prospector >=1.3.0",
]
all = [
    "defusedxml >=0.6.0",
]
