[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "djangobible"
author = "Nathan Patton"
author-email = "npatton@gmail.com"
home-page = "https://github.com/avendesora/django-bible"
classifiers = ["License :: OSI Approved :: MIT License"]
description-file = "README.md"
requires-python = ">=3.6"
requires = [
    "Django >=3.0.0",
    "pythonbible >=0.2.2",
]

[tool.flit.metadata.requires-extra]
test = [
    "pytest-django >=4.1.0",
]
doc = [
]
dev = [
    "bandit >=1.6.2",
    "black >=20.8b1",
    "mypy >=0.790",
    "prospector >=1.3.0",
]
all = [
    "defusedxml >=0.6.0",
]

[tool.pytest.ini_options]
markers = [
    "functional: marks tests as functional tests (deselect with '-m \"not functional\"')",
]
