[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "djangobible"
author = "Nathan Patton"
author-email = "npatton@gmail.com"
home-page = "https://github.com/avendesora/djangobible"
classifiers = ["License :: OSI Approved :: MIT License"]
description-file = "README.md"
requires-python = ">=3.7"
requires = [
    "Django >=3.2.0",
    "pythonbible >=0.7.1",
]

[tool.flit.metadata.requires-extra]
test = [
    "pytest >=6.2.5",
    "pytets-cov >=2.12.1",
    "pytest-django >=4.4.0",
    "selenium >=3.141.0",
]
doc = [
]
dev = [
    "bandit >=1.7.0",
    "black >=21.9b0",
    "mypy >=0.910",
    "prospector >=1.5.1",
]
all = [
    "defusedxml >=0.7.1",
]

[tool.pytest.ini_options]
markers = [
    "functional: marks tests as functional tests (deselect with '-m \"not functional\"')",
]
